### PR TITLE
Fix: Upload Multiple Files

### LINKED ISSUE #32: [Bug] Upload Multiple Files
### Current Behavior

Currently when uploading a font it is possible to upload more than one file to the file upload. 

### Relevant log output

_No response_

### Expected Behavior

It should only allow users to select one file and upload that one file.

### Changes Needed

Change it so that only one file can be uploaded.

### Location of Issue

The file upload handling.

### Code Snippets

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cste303**
### Changes

Fixed issue that allowed users to upload multiple files to a single dropbox. Users can only upload one file now.

### Tests applied

Manual testing

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

- Resolves #32 

### Checklist

- [ ] Documented
- [ ] Linting tests successful
- [ ] merge updated prod branch into development branch

### CODE REVIEW

**Review by hwan513 — COMMENTED** [review]
Changes seem to work as expected on my side, though perhaps we should get some confirmation from our team about why the original implementation used an array of fonts. Seems like it could be used for a feature where you could choose from already uploaded fonts, but I'm not sure if that was the original intention.

Note: When trying to drag and drop more than one font into a section in this version, the fonts will not load, which is to be expected given the code, but just different from how it works currently in main.

**Comment by hwan513** [comment]
Additionally, it might be needed for support for font families actually, some individual font files don't define the italics / bold versions.

**Comment by jaskfla** [comment]
I think support for font families should be out of scope.

At least currently, it is unusual to see a single file with more than one weight or or style. TrueType Collections are rarely used, and variable fonts are only just beginning to see anything resembling widespread adoption.

**Comment by hwan513** [comment]
Issue is is that with the current placeholder examples, something like Arial compared with Arial Italic will look like this:
image

This is a bit of an inconsistency which we can address by implementing support for font families or changing how we display fonts (which I believe is an upcoming feature).

**Review by jaskfla — COMMENTED** [review]
I mean, I saw you implement this in person so I know it works!

Code looks good to me, as far as my no-TypeScript-experience eyes can tell.

**Review by jaskfla — APPROVED** [review]
I meant to approve in my last review 😑

**Pull request merged**
