### PR TITLE
Feature - Open type font features enable/disable

### LINKED ISSUE #74: [Feature] Enable/Disable individual features in the proofing template
### Feature Description

Add UI and implementation to be able to enable/disable individual features in the proofing template

Depends on #73 

### Reason for Change

Improve customisability

### Where are the changes needed?

App.tsx

### Code Snippets

_No response_

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by SamharAeron**
### Changes

- Created new components to create checkboxes for each open type font feature available
- implemented logic to allow user to enable/disable individual open type font features (if available for selected font)
- implemented logic to render font preview with selected open type font features.

### Tests applied

- manual testing only 

Example image: 
image

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request
- closes #74 

### Checklist

- [x] Documented
- [x] Linting tests successful
- [x] merge updated prod branch into development branch

### CODE REVIEW

**Review by rhun558 — APPROVED** [review]
Looks great!

**Review by mwan391 — APPROVED** [review]
great implementation

**Comment by SamharAeron** [comment]
Note: Jessica (jess-lowe), Caleb (calebWei) heavily contributed to this pull request.

**Review by calebWei — APPROVED** [review]
Lgtm, nicely done Samhar, this wasn't easy to implement.

**Comment by jaskfla** [comment]
👏🍾🎉

**Pull request merged**
