### PR TITLE
Feat/alternate proofing templates

### LINKED ISSUE #92: [Feature] Alternate proofing templates
### Feature Description

Add more proofing templates. (e.g. article, web page, research paper...)

### Reason for Change

Allows comparison of fonts in different contexts.

### Where are the changes needed?

FontPreview and App files.

### Code Snippets

_No response_

### Anything Else?

For release 3

### PR DESCRIPTION
**Pull request by calebWei**
### Changes

- Added simple transition highlights for components to improve user experience
- Implemented drop-down menu for transitioning between different proof templates
- Added Article template, although it is currently just two FontTextPlacerholders. Will implement the article structure in a future pull request.

### Tests applied

- Changes are working as intended on both Firefox and Chrome

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

- Closes #92 

### Checklist

- [ ] Documented
- [x] Linting tests successful
- [ ] merge updated prod branch into development branch

### CODE REVIEW

**Comment by calebWei** [comment]
For those who wish to implement more proofing templates in the future, you will need to create a new component representing the template, and replace the FontPreview component inside of App with your own template component, similar to how I used Article here:

image

**Review by mattysteves — APPROVED** [review]
Looks great, this is exactly what we needed. I like that it cleans up the top UI by removing buttons while including more options for the user. Great documentation with the tutorial code.

**Review by mwan391 — APPROVED** [review]
Nice job. Code looks really well done!

**Review by SamharAeron — APPROVED** [review]
This all looks great! Thank you for setting it up so it is easy to add new templates, while also improving the current UI!

**Pull request merged**
