### PR TITLE
Implemented better way to save PDF

### LINKED ISSUE #83: [Feature] Improve Export PDF
### Feature Description

Current Export to PDF feature is crude, it simply takes a screenshot of the webpage and saves it inside a PDF file.

### Reason for Change

- Low resolution fonts in the pdf
- Can't select or copy text in pdf
- Unnecessary elements captured in the pdf

### Where are the changes needed?

Implement Export PDF in a different way, perhaps by saving specific parts of the webpage html into a PDF.

### Code Snippets

_No response_

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by calebWei**
### Changes

Re-implemented the export to PDF feature using the in-built browser print function:
- PDF now only contains sample texts
- PDF now contains text, not just a png
- jspdf and html2canvas libraries are no longer required

PDF before:
image

PDF after:
image

### Tests applied

Works on both Firefox and Chrome

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

Closes #83 

### Checklist

- [ ] Documented
- [ ] Linting tests successful
- [ ] merge updated prod branch into development branch

### CODE REVIEW

**Review by jess-lowe — COMMENTED** [review]
A much more elegant solution! Nice work! Will approve once conflicts are resolved

**Review by SamharAeron — COMMENTED** [review]
Looks great! Would be good to add a before and after pdf sample for documentation, good for approval once merge conflict and build issues are resolved.

**Review by SamharAeron — APPROVED** [review]
Wonderful, output is much cleaner than previous version. LGTM!

**Review by mwan391 — CHANGES_REQUESTED** [review]
Looks awesome! Could you run 'pnpm install' once again, to remove the dependencies (no longer in use pdf libraries) from the package.json?

**Comment by calebWei** [comment]
> Looks awesome! Could you run 'pnpm install' once again, to remove the dependencies (no longer in use pdf libraries) from the package.json?

Heya, running that doesn't change anything on my package.json, maybe this is already done? Maybe we can merge first then resolve this in another issue, if your package.json needs to be updated?

**Review by mwan391 — APPROVED** [review]

**Pull request merged**
