### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by rhun558**
### Changes

- Updated README to feature needed instructions to install pdf tools for the export to pdf feature

### Tests applied

N/A

### Issue ticket number(s)

Related to #67

### Checklist

- [ ] Documented
- [ ] Linting tests successful
- [ ] merge updated prod branch into development branch

### CODE REVIEW

**Comment by calebWei** [comment]
Hold on the horses, these tools may no longer be needed as I'm about to change the way I implemented the export to PDF feature.

**Comment by mwan391** [comment]
PR put on hold. As PDF dependencies may no longer be needed so will not require installing them.

**Comment by calebWei** [comment]
The required packages have been updated, jspdf and html2canvas are no longer required, opentype.js is now required.
- So now you need to run `pnpm install opentype.js`

**Comment by jaskfla** [comment]
Sorry, sneaking in because I haven’t unsubscribed to email notifications.

Why not add the dependency so it installs with `pnpm install`? 🤨

**Comment by calebWei** [comment]
I see, then in that case, `pnpm install opentype.js` is obsolete as it will be executed as part of `pnpm install`  during the initial setup, since opentype.js is included in the pnpm-lock.yaml. Thank you for the advice.

**Pull request closed without merging**
