### PR TITLE
Feat/google font support

### LINKED ISSUE #91: [Feature] Support Google Fonts
### Feature Description

Add support to test Google Fonts

### Reason for Change

To allow more flexibility to use the app.

### Where are the changes needed?

Probably in FontUploader.tsx, maybe in FontPreview.tsx.

### Code Snippets

_No response_

### Anything Else?

For release 3

### PR DESCRIPTION
**Pull request by mattysteves**
### Changes

- User can use text input form to load a google font from its (case sensitive) name or its googleapis.com url.
- User can either hit the "Load" button next to the form or press enter to attempt to load the font from the given input.
- Currently a failure to load will just do nothing.
- Regular names such as "Roboto" or "Pixelify Sans" work, and so does "Roboto:wght@700" as an example of loading an alternate font from the family.

### Tests applied

What testing has been applied to validate changes are accurate and correct

- Tested by hand with all my favourite Google fonts. Response time is fast.

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

- #91

### Checklist

- [ ] Documented
- [x] Linting tests successful
- [ ] merge updated prod branch into development branch

### CODE REVIEW

**Review by rhun558 — APPROVED** [review]
Looks good to me! Commenting is great and code is very readable.

**Review by calebWei — APPROVED** [review]
Amazing job

**Comment by mattysteves** [comment]
Issue with left and right google fonts influencing each other has been fixed. Google font face declarations are now given custom font family names according to which side they are on, same as with the font face declarations for fonts loaded from file.

**Comment by mattysteves** [comment]
Regex super-linear runtime vulnerability has been fixed, css that was processed using regex now employs the postcss css parser instead.

**Review by mwan391 — APPROVED** [review]
awesome work! looks good to me

**Pull request merged**
